device:
  brightness: medium
  orientation: 180
  sleep_timeout: 30


# Button Layout:
# 0-7: The 8 OLED keys
# 8: The physical button usually labeled with a diamond/layer icon
# 9: The center click of the wheel


layers:
  - name: "General"
    # Blue Ring for General
    color: { r: 0, g: 0, b: 255 }
    wheel_speed: faster
    buttons:
      6:
        label: "Vol -"
        keys: ["KEY_VOLUMEDOWN"]
      7:
        label: "Vol +"
        keys: ["KEY_VOLUMEUP"]
      8:
        # The separate physical button
        label: "Layer"
        keys: ["INTERNAL_LAYER_CYCLE"]
      9:
        # The Wheel Center Click
        label: "Mute"
        keys: ["KEY_MUTE"]
    wheel:
      left: ["KEY_UP"]
      right: ["KEY_DOWN"]

  - name: "DaVinci"
    # Red Ring for DaVinci
    color: { r: 255, g: 0, b: 0 }
    wheel_speed: fast
    buttons:
      0:
        label: "Split"
        keys: ["KEY_LEFTCTRL", "KEY_BACKSLASH"]
      1:
        label: "Join"
        keys: ["KEY_LEFTALT", "KEY_BACKSLASH"]
      2:
        label: "Ripple Del"
        keys: ["KEY_LEFTSHIFT", "KEY_BACKSPACE"]
      3:
        label: "Undo"
        keys: ["KEY_LEFTCTRL", "KEY_Z"]
      4:
        label: "Blade"
        keys: ["KEY_B"]
      5:
        label: "Select"
        keys: ["KEY_A"]
      6:
        label: "Zoom -"
        keys: ["KEY_LEFTCTRL", "KEY_MINUS"]
      7:
        label: "Zoom +"
        keys: ["KEY_LEFTCTRL", "KEY_EQUAL"]
      8:
        # The separate physical button
        label: "Layer"
        keys: ["INTERNAL_LAYER_CYCLE"]
      9:
        # The Wheel Center Click
        label: "Play"
        keys: ["KEY_SPACE"]
    wheel:
      # Frame stepping
      left: ["KEY_LEFT"]
      right: ["KEY_RIGHT"]
