// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupConfig() {
  return window['go']['main']['App']['BackupConfig']();
}

export function ExportConfigToFile() {
  return window['go']['main']['App']['ExportConfigToFile']();
}

export function GetAvailableKeys() {
  return window['go']['main']['App']['GetAvailableKeys']();
}

export function GetBattery() {
  return window['go']['main']['App']['GetBattery']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetDeviceState() {
  return window['go']['main']['App']['GetDeviceState']();
}

export function GetGUIState() {
  return window['go']['main']['App']['GetGUIState']();
}

export function ImportConfigFromFile() {
  return window['go']['main']['App']['ImportConfigFromFile']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ReadConfigFile() {
  return window['go']['main']['App']['ReadConfigFile']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveGUIState(arg1, arg2) {
  return window['go']['main']['App']['SaveGUIState'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function ValidateConfigYAML(arg1) {
  return window['go']['main']['App']['ValidateConfigYAML'](arg1);
}

export function WriteConfigFile(arg1) {
  return window['go']['main']['App']['WriteConfigFile'](arg1);
}
