// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BackupConfig():Promise<void>;

export function ExportConfigToFile():Promise<string>;

export function GetAvailableKeys():Promise<Array<string>>;

export function GetBattery():Promise<main.BatteryStatus>;

export function GetConfigPath():Promise<string>;

export function GetDeviceState():Promise<string>;

export function GetGUIState():Promise<number>;

export function ImportConfigFromFile():Promise<string>;

export function LoadConfig():Promise<main.ConfigDTO>;

export function Quit():Promise<void>;

export function ReadConfigFile():Promise<string>;

export function SaveConfig(arg1:main.ConfigDTO):Promise<void>;

export function SaveGUIState(arg1:number,arg2:number):Promise<void>;

export function ShowWindow():Promise<void>;

export function ValidateConfigYAML(arg1:string):Promise<main.ValidateYAMLResult>;

export function WriteConfigFile(arg1:string):Promise<void>;
